### ISSUE TITLE
http://www.prod-preview.openshift.io/index.html - "Register for Developer Preview" button display is truncated 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/www.openshift.io#16]
![screenshot from 2017-03-19 17-58-07](https://cloud.githubusercontent.com/assets/642621/24087402/d5f77870-0cf4-11e7-89c3-e93c953636b7.png)

**Comment by mindreeper2420** [comment]
Fixed as part of https://github.com/openshiftio/www.openshift.io/pull/15

**Comment by mindreeper2420** [comment]
@ldimaggi can you recheck and verify that this is fixed? thanks!
