### ISSUE TITLE
First logged in screen should be /_home

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/www.openshift.io#27]
Upon logging in, user should be navigated to /_home, not /<userid>.

**Comment by pmuir** [comment]
@mindreeper2420 I assigned this to you - I think I already implemented the redirect, but check on it and change it to /_home I think

**Comment by mindreeper2420** [comment]
@pmuir yes, the redirect is already there, but it sends the user to their profile (http://prod-preview.openshift.io/adamjolicoeur). I'll update.

**Comment by mindreeper2420** [comment]
redirect updated as part of PR #31
