### ISSUE TITLE
Auto navigate from www to /_home if already logged in

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/www.openshift.io#28]
If the user currently has a valid login token, then / should be an auto-redirect/navigation to /_home. However, if the saas is in a known bad state, then do not do so. (e.g., don't redirect from the working marketing page to a 503 /_home page)

**Comment by qodfathr** [comment]
Or, as an alternative if that's too difficult -- when user is logged in and on /, add a link to top navigation named "MY HOME" which goes to /_home

**Comment by pmuir** [comment]
@mindreeper2420 let's start with the alternative and then keep this issue open for the primary.

**Comment by mindreeper2420** [comment]
@qodfathr @pmuir 
Here is the navigation when logged out:
<img width="1920" alt="screen shot 2017-03-25 at 4 13 57 pm" src="https://cloud.githubusercontent.com/assets/4032718/24325744/1ea2b12c-1176-11e7-80d4-5d5468b4b764.png">

Here is the navigation when logged in:
<img width="1920" alt="screen shot 2017-03-25 at 4 13 50 pm" src="https://cloud.githubusercontent.com/assets/4032718/24325748/27376300-1176-11e7-8b07-f7ea88f118de.png">

**Comment by mindreeper2420** [comment]
PR https://github.com/openshiftio/www.openshift.io/pull/37
