### ISSUE TITLE
Make background of Features more distinct

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/www.openshift.io#35]
@mindreeper2420  When #34 is complete, there will be no visible separation between the features list and the top registration area. As such, find a way to visibly make the regions distinct. e.g., a horizontal rule. Or, please consider using a subtle contrasting background behind each feature -- e.g. "An end-to-end" gets light gray, which will separate it from the registration area. "Create continuously deployed" stays white, separating it from the previous feature. "Plan for success" gets light gray again, etc.

Obviously, do whatever makes the most sense to you.

**Comment by mindreeper2420** [comment]
The visuals will be updated once the Visual Design story (referenced above) is completed - should be done by mid-week.

**Comment by mindreeper2420** [comment]
This should be resolved with the merger of the current PR.
