### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/www.openshift.io#44]
Please put following into footer:

Privacy Statement --> https://www.redhat.com/en/about/privacy-policy
Terms and Conditions --> https://www.openshift.com/legal/terms.html
Open Source --> https://fabric8.io
(We'd then want a Contact Us, but we don't have a link for this yet.)
facebook icon --> https://www.facebook.com/openshiftio/
twitter icon --> https://twitter.com/openshiftio

See footer of https://www.openshift.com/ to find icons.

**Comment by mindreeper2420** [comment]
@qodfathr do you want a GitHub link to a specific repo, or just the Facebook and Twitter links? Also, do you have any text in mind for the JOIN US area?

here is the current version, before PR is filed:
<img width="1440" alt="screen shot 2017-03-30 at 5 21 40 pm" src="https://cloud.githubusercontent.com/assets/4032718/24526774/68a21358-156d-11e7-9f9a-29485e63b57d.png">

**Comment by qodfathr** [comment]
No GitHub link, thx.

**Comment by qodfathr** [comment]
I guess this means "join us" as in "join us on social media," and not "join us" as in join our open source community. I think that's a bit confusing.

Can we just simplify for now and move the fb/twitter icon links to the bottom footer? This matches openshift.com, and saves us from having to figure out this text.

**Comment by mindreeper2420** [comment]
@qodfathr created footer to match openshift.com

<img width="1326" alt="screen shot 2017-04-21 at 7 20 47 am" src="https://cloud.githubusercontent.com/assets/4032718/25275408/25d4520a-2663-11e7-8900-4aa3625a04a4.png">

**Comment by mindreeper2420** [comment]
fixed in PR https://github.com/openshiftio/www.openshift.io/pull/93
