### ISSUE TITLE
Explore Link?

### ISSUE THREAD

**Issue by mindreeper2420** [openshiftio/www.openshift.io#57]
@qodfathr Where should the Explore link land when a user clicks on it but is not logged in? Is there a default profile or page that should be set as the landing place?

**Comment by qodfathr** [comment]
Let's remove for now. This will take some work.

**Comment by mindreeper2420** [comment]
Do you want to keep the 'Features', 'Red Hat Developers', and 'Community' or remove those as well for the time being?

**Comment by qodfathr** [comment]
RHD can stay and link to d.r.c.
Community is trickier -- it's in the footer with 3 links, so not sure what to do about this one. If 'Community' was it's own section on this page, or even it's own full page, I'd say link there. But as it's current part of a larger div at the bottom of the page, there is really no good way to link this one as it stands.

Remove it.
