### ISSUE TITLE
logging with Firefox presents the user with a blank screen

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/www.openshift.io#68]
This happens at the 18 second mark of the referenced screencast:

https://drive.google.com/open?id=0B1s-ZoxD8FjUcmRqSlpUQXBzT3M

**Comment by mindreeper2420** [comment]
@ldimaggi please clear you cache and try again - I am not able to replicate this issue on Firefox.

**Comment by ldimaggi** [comment]
Moved to:
https://github.com/fabric8io/fabric8-ui/issues/762
