### ISSUE TITLE
Enhancement request - to facilitate automated UI creation - add unique (within each page) ID's to UI elements 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/www.openshift.io#69]
The UI at present is difficult to work with for automated test creation - multiple elements share the same ID, path, selectors - for example:

![screenshot 63](https://cloud.githubusercontent.com/assets/642621/24676288/64cd2308-1950-11e7-9be5-7417513e20c8.png)

**Comment by mindreeper2420** [comment]
@ldimaggi I believe that this belongs in https://github.com/fabric8io/fabric8-ui. This repo is just for the home page.

**Comment by ldimaggi** [comment]
Moved to:
https://github.com/fabric8io/fabric8-ui/issues/761
