### ISSUE TITLE
On prod-preview.openshift.io, home page 'create a space' options are not operational 

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/www.openshift.io#84]
Workaround - Spaces can be created through the logged in user's profile.

Clicking on the 'create a space' options on the home page does nothing.

**Comment by ldimaggi** [comment]
Originally logged here:
https://github.com/fabric8io/fabric8-planner/issues/1638

**Comment by mindreeper2420** [comment]
@ldimaggi this issue is part of the work in https://github.com/fabric8io/fabric8-ui and is still in progress. What you are seeing is just the HTML - nothing is wired up yet.

**Comment by ldimaggi** [comment]
Moved to:
https://github.com/fabric8io/fabric8-ui/issues/758
