### ISSUE TITLE
Legal changes for footer

### ISSUE THREAD

**Issue by qodfathr** [openshiftio/www.openshift.io#98]
Privacy Statement --> keep as-is
Terms of Use --> Rename to Service Terms, keep link as-is
ADD Terms of Use : link to https://www.redhat.com/en/about/terms-use
All policies and guidelines --> keep as-is

Revised should look like:
Privacy Statement | Service Terms | Terms of Use | All policies and guidelines

**Comment by mindreeper2420** [comment]
resolved with PR https://github.com/openshiftio/www.openshift.io/pull/100
